app_port = 8_000

[database]
host = "127.0.0.1"
port = 5_432
username = "postgres"
password = "123456."
database_name = "bongo"

[redis]
redis_url = "redis://default:redispw@localhost:32769"

[jwt]
expiration = 24